print(" ```````` `-...`````````` ``````-.`.:--:/---/:...-/.....-``.../.``o/.````````````` ``.````````-`.. -")
print("``````````.--.```` ``````````.``:.--//+////++---:o:.-.-.-..-//-``.+/-````````````` .-.````````-`.- -")
print("``````````.-.````````````````.../--:+oyssssss+//oso++//++///s+/...:/:.``````...``` ./-````````-`.- -")
print("```..`````-/.`````````.```````.-/-:/osdNNNmdy+//+///////+ossyhy+/:+o-..``````.```` .:-````````-``. -")
print("```.``````:+.` ````` `.```````--///+shhdmmdhh+//oys++///+ossyosossyh+:-.``` .````  -.``.``````-`.. -")
print("```. `````-:.. ````` `-.````..:/+ooooo++oooos/::oso+oososyhhhhs+++sys++/-`` ...``  :--.```` ``-``` -")
print("```. `````-:.` ````` `...```.:/+so+//++///+oo/::+so++/+ohmmNNmhssoyysso+/-` `..``  ---````` ``-`.` -")
print("`.`. ` ```/:.` ````` `...``.:/oso///:/+:::/+/::-+oooso++ydmmmddhhyhyssyso:.`...``  :-/`` `` ``:`.. -")
print("`.`. . ```/:.  ````` `.-.`.-/oyso+/:///--::+/-::oys/++++yyddmmddmdhyyyhhy+-`...``  -/:`` `` ``-`.` -")
print("```.`` ` `::.  ````` ` ` `:/shhys++:::/::/oss///sys++oooysyohdsshmmhdmmddo:....``  .+/ `  ` ``.``` .")
print("```.`` ` `::`  ````` ` ``.:/hdhyyo+:+sy+++oys///sss+//::++hhyhhyyhNNNNMNmh/.....`  `/: ` `` `````   ")
print(".`.-`. ` `:/`  `.`.. ` `.-/odmdhyooooso:::+so:::osyooo++yhhsdddhydmmNMMMNd+--.`.`  `.. . `` ```.`   ")
print(". ..`. ` `-:`  .` .` ` .:+oymmmhyys+++o///oyyssoyyhyyhdmmdyoyhhhyhddhNNNNhs:-.`..  .-- . `` `` .`   ")
print(". `. ` ` `..   .` `` ``.-+hdNNmddys+osy+++yhyoosddmdyhdmddyoosysyhhhydNNNds/-.`.`  .+/ `  ` `` ``   ")
print(".  . ` ` `..   .`  ` ``:/oydmNmmdhyssyhyyyyyyyhhhdh+://yhy+/++s+/oyyyydmdds/-` ..  -:: ` `` `  ..` .")
print(".  . . ` `.-   `.  . . -/oydmNddhdddddmdhhhddsoo+/:.-:/ssy++//:::syysyhddhy+-  .`  -:: ` `` .  ..`  ")
print(".  - . `  `-   .`  . . -/+hmmNdhhddmdhhyssoo+//:-..-.::++oo+oso+shddyyshmdho-` ..  -:/ ` ```.  `.   ")
print(".  ` . .  ..   ..    . -::ymNdssyssshyhyyo:+/.---`.-`-://+shdhs+yyhhhyyhmNmo.` ..  `/- ` ``    ..   ")
print(".  ` .    .-   ..    . .-/dNdhso//++oo+/oo+ss:-.. ..`-/+o+++///---so//+yhdNh:  ..   --`  ``    ..   ")
print(".  ` .    .-   ..    . `.:dmdo/-:/:-:/:--..:++yo- ...oy+/-..://- `+::-:+hhdd-  ..   .-`  ``    .-`  ")
print(".  ` .    `-   ..    . `..yNh+--///-:---:..--shy: ..-shs--..///.``-----/sdmh.` ..  -::   ``    ..`  ")
print(".  ` -    `-   ..    . ``.sNmo::///---.:--:oyyhy-`.:.ydys+.`-//-``---..:+dms.  ..  -//   ``    ..   ")
print("-    -    `.   .-    . ```ommdsoo++///:/::ydydyy/-os/shhshs.`--:..:--..:ydho`  -.  -/:   ``    -.   ")
print("-  ` .    ``   `-    .   `/hhhhmmdddddyyyddhy+//.:+syoooshhhoosyssshyhshddy/   .   `/-   ``    .    ")
print(".  ` .    ``    .    .    :oo++hmNMMNNmhhso+////-`/oyho:-:+shhdyhdddddddhy+.   .    :-   ``    .    ")
print(".  ` .    ``    .    .    -++//smNMMNNdso////:+:``-s+oh+--::/+ydmhys+/::+/:`   .   .+-   ``    .    ")
print(".  ` .    ``    .    . `` .://+hdNNNmdhyo///:-+-``:sood+::/+oyhddhyhy/-:/:-    .   `-.   ``    .    ")
print("`  ` .     .    `    . `` `---:yhdmNNNmdy++:-.`...:oo++:::/sdmmNNmddd/--:..    `   ``.   ``    `    ")
print(".  ` .     .    .    . `` ...../oosshhhshyo::.``` .--:////odmmNmho++/-.`.``    .     `   ``    .    ")
print(".  ` .     .    .    . `` ...``-/+++shdooydo/.````-:-:+//oydNmNdo::::`   `.    .         ``    .    ")
print(".  ` .     ``   .    . `` `..` .:://+hmhhsh::..`---:://+/+smNNNm/.:-.    `.    .         ``    .    ")
print(".  ` .     .    .    .    ..`` `..--/syhdmh//..-..:/-:oyhhhmNNdo-``..    `.    .         ``    .    ")
print(".  ` .          .    .    `.`   ..- ./+hNNdoo/:/::/:-+hhhsomNNy/.  ..     `    .         ``    .    ")
print(".  ` `          .    `    `.`   ...  -:sdmdyh++o+oyyooohoydmmdy:`  ..     `    .         ``    .    ")
print(".    .          .    .    ```   -..  `-:ymhoh/hdhydysdhoohhymh+:   `.    `.    .         ``    .    ")
print(".    .          .    .    ..`   ...   `-+yh/y-oy:/ds.sy/:yoyds:.   ..   ``.    .         ``    .    ")
print(".    .     `    .    .    `.`   .--``` .//+:+.:/-:+/./+:-+:+o+-.   ..   .``    .    `    ``    .    ")
print(".    `     .    .    `    `.`   ...     --:-/.-:.-/:.::-`:-::-..   ..   . `    .    .    ``    .    ")
print(".  `       .    .         `.`   ...     .``.:`.-``::`--` .`.....   .`   `      .    .          .    ")





